#!/bin/bash
#----------------------------------------"
# Contributor:  Tobias Holzmann          "
# Last Change:  May 2015                 "
# Version:      3.0                      "
# Email: Tobias.Holzmann@Holzmann-cfd.de "
#----------------------------------------"


#-------------------------------------------------------------------------------


cd ${0%/*} || exit 1

echo "
\"-----------------------------------------\"
\" vim addon for highlight OpenFOAM files  \"
\" Contributor:  Tobias Holzmann           \"
\" Last Change:  May 2015                  \"
\" Version:      3.0                       \"
\"-----------------------------------------\"
"

# Color definition for nice output and playing with bash
#-------------------------------------------------------------------------------
red='\e[0;31m'
green='\e[0;32m'
nc='\e[0m'


# Checking if .vim directories are available and create if bool = false
#-------------------------------------------------------------------------------
if [ ! -d $HOME/.vim ]; then
    mkdir $HOME/.vim
fi

if [ ! -d $HOME/.vim/syntax ]; then
    mkdir $HOME/.vim/syntax
fi

if [ ! -d $HOME/.vim/colors ]; then
    mkdir $HOME/.vim/colors
fi

if [ ! -d $HOME/.vim/syntax/foam256 ]; then
    mkdir $HOME/.vim/syntax/foam256
fi

if [ ! -d $HOME/.vim/indent ]; then
    mkdir $HOME/.vim/indent
fi

if [ ! -d $HOME/.vim/plugin ]; then
    mkdir $HOME/.vim/plugin 
fi

if [ ! -d $HOME/.vim/ftdetect ]; then
    mkdir $HOME/.vim/ftdetect
fi


# Copy files only if the copied files are newer [-u] 
#-------------------------------------------------------------------------------
echo -n 'All necessary files are copied now...'
cp -ur syntax/* $HOME/.vim/syntax/
cp -u ftdetect/* $HOME/.vim/ftdetect/
cp -u colors/* $HOME/.vim/colors/
cp -u plugin/* $HOME/.vim/plugin/
cp -u indent/* $HOME/.vim/indent/
echo 'done'


# Check if .vimrc exist, if not create one and 
# insert stuff, otherwise just add the stuff to the end of the file
# TODO - check if the input lines still available!
#-------------------------------------------------------------------------------
echo 'Checking if $HOME/.vimrc is available'
if [ ! -f $HOME/.vimrc ]; then
    echo -e "   + ${green}Not available \$HOME/.vimrc » its gonna be created${nc}"
    echo -e '   + The following lines will be inserted:'
    echo    '       filetype plugin indent on'
    echo    '       :let g:foam256_use_custom_colors=1'
    echo    '   + If you want to use your own colorscheme set the value to 0 (foam256_use_custom_colors=0)'

    #- Insert the lines
    echo '"- vim Extension OpenFOAM (if you have your own colorscheme set to 0)\nfiletype plugin indent on\n:let g:foam_use_custom_colors=1' > $HOME/.vimrc

else
    echo -e "${red}There is an existing \$HOME/.vimrc file"

    #- TODO more accurate for plugin and indent
    if grep -Fq "vim Extension OpenFOAM" $HOME/.vimrc; then
        echo "Entry of vim Extenion OpenFOAM in $HOME/.vimrc found » nothing to do"

    else 
        echo -e "    ${green}+ The following lines are inserted at the end of the file:"
    	echo    '        filetype plugin indent on'
    	echo -e "        :let g:foam256_use_custom_colors=1 ${nc}"

	#- Insert the lines
	echo '"- vim Extension OpenFOAM (if you have your own colorscheme set to 0)\nfiletype plugin indent on\n:let g:foam_use_custom_colors=1' >> $HOME/.vimrc
    fi
fi


# All done, say goodbye and be polite
#-------------------------------------------------------------------------------
echo -e "${nc}
vimExtensionOpenFOAM is ready to use...
Have a nice day... 
Tobias Holzmann"


#-------------------------------------------------------------------------------
