#!/bin/bash
#"----------------------------------------"
#" Contributor:  Tobias Holzmann          "
#" Last Change:  October 2014             "
#" Version:      2.0	                  "
#" File:         install                  "
#"----------------------------------------"
#
# If the script is not working, put the files into the right folders
# openfoamcolor*.vim ---> $HOME/.vim/colors/ 
# openfoam.vim       ---> $HOME/.vim/syntax/
# scripts.vim        ---> $HOME/.vim/
# insert ':set tabstop=4 shiftwidth=4 expandtab' to .vimrc » if the file does not exist create it

cd ${0%/*} || exit 1  # run from this directory

echo "
\"----------------------------------------\"
\" vim addon for highlight OpenFOAM cases \"
\" Maintainer:   Tobias Holzmann          \"
\" Last Change:  October 2014             \"
\" Version:      2.0                      \"
\"----------------------------------------\"
"

# color definition
red='\e[0;31m'
green='\e[0;32m'
nc='\e[0m'

# Checking out the .vim directory and create if not exist
if [ ! -d $HOME/.vim ]; then
	mkdir $HOME/.vim
fi

if [ ! -d $HOME/.vim/syntax ]; then
	mkdir $HOME/.vim/syntax
fi

if [ ! -d $HOME/.vim/colors ]; then
	mkdir $HOME/.vim/colors
fi

# Checking out the files for update

cp -u syntax/openfoam.vim $HOME/.vim/syntax/
cp -u scripts.vim $HOME/.vim/
cp -u colors/* $HOME/.vim/colors/

if [ ! -f $HOME/.vimrc ]; then
    echo -e "${green}No \$HOME/.vimrc found » created${nc}"
    echo ":set tabstop=4 shiftwidth=4 expandtab" > $HOME/.vimrc
else
    echo -e "${red}There is an existing \$HOME/.vimrc file" 
    echo -e "${green}The following lines are insert to the last line: ':set tabstop=4 shiftwidth=4 expandtab'${nc}"
    echo ":set tabstop=4 shiftwidth=4 expandtab" >> $HOME/.vimrc
fi


echo -e "
vimExtensionOpenFOAM is ready to use...
Have a nice day... 
Tobias Holzmann"

