#!/bin/bash
#"----------------------------------------"
#" Contributor:  Tobias Holzmann          "
#" Last Change:  November 2014            "
#" Version:      2.1	                  "
#" File:         install                  "
#"----------------------------------------"


cd ${0%/*} || exit 1  # run from this directory

echo "
\"-----------------------------------------\"
\" vim addon for highlight OpenFOAM files  \"
\" Contributor:  Tobias Holzmann           \"
\" Last Change:  November 2014             \"
\" Version:      2.1                       \"
\"-----------------------------------------\"
"

# color definition
red='\e[0;31m'
green='\e[0;32m'
nc='\e[0m'

# Checking out the .vim directory and create if not exist
if [ ! -d $HOME/.vim ]; then
	mkdir $HOME/.vim
fi

if [ ! -d $HOME/.vim/syntax ]; then
	mkdir $HOME/.vim/syntax
fi

if [ ! -d $HOME/.vim/colors ]; then
	mkdir $HOME/.vim/colors
fi
if [ ! -d $HOME/.vim/syntax/openfoam ]; then
	mkdir $HOME/.vim/syntax/openfoam
fi

# Checking out the files for update

cp -ur syntax/* $HOME/.vim/syntax/
cp -u scripts.vim $HOME/.vim/
cp -u colors/* $HOME/.vim/colors/

if [ ! -f $HOME/.vimrc ]; then
    echo -e "${green}No \$HOME/.vimrc found » created${nc}"
    echo $'"- vim Extension OpenFOAM\n:set tabstop=4 shiftwidth=4' >> $HOME/.vimrc

else
    echo -e "${red}There is an existing \$HOME/.vimrc file"

    if grep -Fq "vim Extension OpenFOAM" $HOME/.vimrc; then
        echo "Entry of vim Extenion OpenFOAM in $HOME/.vimrc found » nothing to do"

    else 
        echo -e "${green}The following lines are insert to the last line: ':set tabstop=4 shiftwidth=4 expandtab'${nc}"
        echo $'"- vim Extension OpenFOAM\n:set tabstop=4 shiftwidth=4' >> $HOME/.vimrc
    fi
fi

echo -e "${nc}
vimExtensionOpenFOAM is ready to use...
Have a nice day... 
Tobias Holzmann"

